apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-scale-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-apps
rules:
  - apiGroups: [""]
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-apps_auto-scale-robot
roleRef:
  kind: Role
  name: scale-apps
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: auto-scale-robot
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: selenium-grid-4
    name: selenium-k8s-node-scaler
  name: selenium-k8s-node-scaler
spec:
  containers:
  - env:
    - name: SELENIUM_VIDEOS_PATH
      value: /videos
    image: krisek11/selenium-k8s-node-scaler
    imagePullPolicy: IfNotPresent
    name: selenium-k8s-node-scaler
    command: [ "/bin/bash", "-c", "--" ]
    #args: [ "while true; do echo -n .; sleep 30; done;" ]
    args: [ "cd /usr/lib/selenium-k8s-node-scaler/; python3 selenium-k8s-node-scaler.py" ]
    resources:
      limits:
        cpu: "0.5"
        memory: 0.5Gi
      requests:
        cpu: "0.2"
        memory: 0.2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /videos
      name: videos
  serviceAccountName: auto-scale-robot
  volumes:
  - name: videos
    persistentVolumeClaim:
      claimName: "selenium-pvc"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: selenium-k8s-test-results-nginx-default-conf
data:
  default.conf: |
    server {
      listen 8000;
      location / {
          root /var/www/html;
      }    
    }
  index.html: |
    Hello World!
---
apiVersion: v1
kind: Pod
metadata:
  name: selenium-k8s-test-results
  labels:
    app: selenium-k8s-test-results
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
    volumeMounts:
    - name: nginx-default-conf
      mountPath: /etc/nginx/conf.d/default.conf
      readOnly: true
      subPath: default.conf
    - name: index-html
      mountPath: /var/www/html/index.html
      readOnly: true
      subPath: index.html
    - name: videos
      mountPath: /var/www/html/videos
    livenessProbe:
      httpGet:
        path: /
        port: 8000
    readinessProbe:
      httpGet:
        path: /
        port: 8000
    ports:
      - name: port8000
        containerPort: 8000
        protocol: TCP
  volumes:
  - name: nginx-default-conf
    configMap:
      name: selenium-k8s-test-results-nginx-default-conf
      items:
      - key: default.conf
        path: default.conf
  - name: index-html
    configMap:
      name: selenium-k8s-test-results-nginx-default-conf
      items:          
      - key: index.html
        path: index.html
  - name: videos
    persistentVolumeClaim:
      claimName: "selenium-pvc"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
